### ISSUE TITLE
[Android][BUG]Wrong Cover

### ISSUE THREAD

**Issue by acocalypso** [jpd002/Play-#240] opened 2015-07-20 13:02 UTC
I tried latest weekly and figured out that I have some wrong Covers for .elf files
For fire.elf Im getting the image of the Fire Heroes game and for the quake homebrew .elf Im getting the Quake III Cover.

Is there a possibility to check for the game ID

**Comment by Thunder07** [comment] 2015-07-20 14:00
That's because it's using the file name. 

Unfortunately that has it limits, I'm currently working on a method to use game ID instead. 

But for elf, I don't imagine you'd ever be able to get a cover since the elf itself tends to be the ID.

**Comment by acocalypso** [comment] 2015-07-20 14:06
I can send a prove if you want to
Am 20.07.2015 4:00 nachm. schrieb Thunder07 <notifications@github.com>:That's because it's using the file name. 

Unfortunately that has it limits, I'm currently working on a method to use game ID instead. 

But for elf, I don't imagine you'd ever be able to get a cover since the elf itself tends to be the ID.

**Comment by Thunder07** [comment] 2015-07-20 14:15
There is no need, The Issue is know, I for one am getting a picture of NCAA Final Four 2001 for Final Fantasy Type 0 (a psp game :p)

**Comment by LinkofHyrule89** [comment] 2015-07-20 15:01
@jpd002 is working on a method to pull the game ids from the games Wren the app starts so that can be used for the search instead however if you have working cover for that feel free to submit a pull request we appreciate any help from other developers.

**Comment by Thunder07** [comment] 2015-07-20 15:09
@LinkofHyrule89 a pull request why?  
There currently isn't a method to load a custom cover nor if there was will the cover be made part of the app itself, thus no need for any pull requests.

**Comment by LinkofHyrule89** [comment] 2015-07-20 16:51
Sorry for the confusion I was replying to @acocalypso because he said he was working on a way to get the game id.

**Comment by Thunder07** [comment] 2015-07-20 17:04
@LinkofHyrule89 I think you're still confused, I think your read his quotation of me saying I'm working on a way :p

**Comment by acocalypso** [comment] 2015-07-20 17:07
no im not working on a possible fix for that :D

**Comment by LinkofHyrule89** [comment] 2015-07-20 17:11
Oh OK lol that makes sense.

**Comment by jpd002** [comment] 2015-08-01 05:12
That's been fixed in the previous weekly build (2015-07-26) which has largely improved game detection.

**Closed by jpd002** 2015-08-01 05:12 UTC
