### ISSUE TITLE
Any new builds/updates of Play! soon?

### ISSUE THREAD

**Issue by mantlebreath** [jpd002/Play-#24] opened 2015-03-15 14:15 UTC
I checked the website and the latest build of Play! is from 2011, which is almost 4 years from now and is when this project was only Windows focused. Now there's WIP with Android, and OS X is right up to par, no?

I was just generally wondering if there will be official builds updated anytime soon, whether on the site or here on GitHub. I see there's an Android branch, so maybe someone can work on an Alpha test build with the GS handler or something? And since OS X is back up to speed, maybe a build of that can be made to test?

Would be interesting to know if you plan on doing this and updating your site and such with info/screenshots.

**Comment by jpd002** [comment] 2015-03-16 02:44
Yeah, I'm currently working on setting up build servers that I will use to generate builds easily. I'm still not sure about the release frequency, but I guess weekly builds would be nice.

**Comment by duskgao** [comment] 2015-03-16 11:18
how about the android port? any news?

**Comment by openglhk** [comment] 2015-03-17 12:05
i have a android build, but i need a"demo2d.elf" image for testing...

**Comment by mantlebreath** [comment] 2015-03-17 18:50
Just use the Torus homebrew or the teapot one; you can find it on Git and compile the sample and test the resulting .elf. Either that or try one of the dozens of .elf homebrews that one could at least work with.

**Comment by MoochMcGee** [comment] 2015-03-17 18:59
Eh, Torus is a bit glitchy in Play!. The torus likes to spaz out a bit.

**Comment by mantlebreath** [comment] 2015-03-17 19:06
There are simpler homebrew than Torus that will possibly work better, depending on how mature the GS handler is on Android.

**Comment by jpd002** [comment] 2015-03-18 03:46
With the latest commits done on the Android branch, demo2b is now running on a device:
![img_0271](https://cloud.githubusercontent.com/assets/6760433/6702293/baed4884-ccff-11e4-8196-a5d24585a717.JPG)

You can get the demos I use to test the Android port here:
http://purei.org/downloads/ps2demos/

**Comment by xiushudongfang** [comment] 2015-03-18 04:10
Is there an auto-build for android or someone can give me android build.

**Comment by openglhk** [comment] 2015-03-18 08:50
Thank you for that elf image
But i got some error when click "Start Tests" button
Called unimplemented OpenGL ES API

**Comment by jpd002** [comment] 2015-03-19 04:41
Humm, that's weird... Do you have more information about the error? 

An OpenGL ES 3.0 compatible device is needed to run the emulator, but I'm not using fancy GLES 3.0 functions at the moment, so, I don't see how you would get an error about an unimplemented OpenGL ES API.

**Comment by openglhk** [comment] 2015-03-19 09:03
Sorry about that, that's my fault..
i forget to update the Play-Framework library

**Comment by openglhk** [comment] 2015-03-19 15:54
![screenshot_2015-03-19-23-52-38](https://cloud.githubusercontent.com/assets/4585760/6734447/24748634-ce93-11e4-9680-2b167a5baea5.png)
Working on my Nexus9 (Tegra K1, Denver)
but cannot display anything on Nexus5 (Snapdragon 800)

**Comment by jpd002** [comment] 2015-03-20 04:49
Nice! I'm glad to see that someone got to build the Android version successfully!

Quite odd for the Nexus 5 though. Does anything show up in log cat? Maybe it fails because of the way I handle the surface I use to create the OpenGL context. I'll have to get myself another device to see if I can reproduce the problem.

**Comment by jpd002** [comment] 2015-03-20 04:52
Also, the latest version now has a file selector which allows testing other ELF files without recompiling. I've only tested "demo2b", "demo2c" and "demo2d" for now. Others will probably crash the emulator since there's still lots of work to be done in the JIT compiler for ARM.

**Comment by MoochMcGee** [comment] 2015-03-20 19:20
@jpd002 Adreno drivers for Snapdragon devices are utter shit when it comes to GLES 3.

**Comment by mantlebreath** [comment] 2015-03-21 04:36
Great news. Also, couldn't ISO 9660 image loading be easily portable between Android/Windows?Just wondering because it's one of the easiest parts of the emulator. It should work with JNI, no?

I'll await for more info about the up-to-date Mac port and how it fares too.

**Comment by Fadi5555** [comment] 2015-03-21 22:56
Congrats! For android users
Please give us a bulid for ios port. Please
You can't imagine how we all exciting about your amazing project.

Or do a port as a core on libretro for retroarch

**Comment by mantlebreath** [comment] 2015-03-22 00:05
iOS port would need Cocoa Touch and OpenGL ES, plus a jailbroken device for dynamic recompilation. 

The same JIT could be used in Android and iOS for the most part, but it should be easy to work off from the Android build.

**Comment by jpd002** [comment] 2015-03-22 01:56
@mantlebreath Yeah, disk image loading should work as it is right now. But there's still lots of work to be done on the compiler to make a real game work, so I haven't bothered adding a way of loading disk images from the UI yet.

**Comment by mantlebreath** [comment] 2015-03-22 02:07
Good point. Something as basic as loading the ISO would be easy compared to improving the dynarec.

**Comment by Fadi5555** [comment] 2015-03-22 08:09
What is cocoa touch?
As you make android port you can make ios port of it. Like ppsspp.

So it's my pleasure to be your tester of ios port of play!

I have (ipad air 2 with 2 GB of ram jailbroken you can't imagine how was ppsspp run so fast and smooth on it)
I'm sure it'll run very good on it too)

if you can give me the build to test it and give you my report.

**Comment by Fadi5555** [comment] 2015-03-22 08:50
I told the people including my classmates in the work and friends as well. about the fantastic project (play! Ps2 emu) it'll come to ios and other platforms
So they feel super exciting about it.

Of course you've done the build on windows and android as well so the next target are ios and mac. After that To be weekly or daily update like ppsspp. Because this project is an open source for multi platforms.

As i told you. it's my pleasure to be an iOS tester. And give you the feedback about it

Please keep your doing up.

**Comment by mantlebreath** [comment] 2015-03-22 17:38
@Fadi5555 Well I didn't really make anything with regards to this emulator, but I don't have an iDevice to test it with or a Mac, so even if I wanted to I couldn't actually do anything. I think maybe you could ask @jpd002 if he has the necessary device to test future iOS ports on. Cocoa Touch is the programming API to develop software for iOS. If I had an iPad Air 2 and a Mac, I'd be tempted to try something, but I can't offer help if I don't have the hardware or end-device to run anything on. Sorry.

**Comment by Fadi5555** [comment] 2015-03-22 17:53
Thank you for replay.
I hope if someone like your friends have iOS devices to test it. I'm sure you'll get high performance on it. Specially the latest one.

So for now i should ask jpd002 to give me the bulid or files to test it and give him a report.

**Comment by destructorrph** [comment] 2015-03-23 00:11
Will you be porting it to Libretro? Also how many games does it work with?

**Comment by mantlebreath** [comment] 2015-03-23 00:20
@destructorrph I doubt any commercial game will work at all; only some homebrew work so far, but it's a good start. The GS, I believe, is among few things that will need decent improvement to work in those stages.

**Comment by destructorrph** [comment] 2015-03-23 00:24
Is GS the graphics driver? I have high hopes for this!

**Comment by mantlebreath** [comment] 2015-03-23 00:36
@destructorrph The GS/Graphics Synthesizer is the PS2 graphics hardware that will need more advanced emulation to run commercial games that depend on advanced graphics to work, like alpha blending and textures; however, the GS alone isn't enough, as you need the CPU and its two vector CPUs efficient as well.

**Comment by jpd002** [comment] 2015-03-23 02:39
Yes, @mantlebreath is right, the Android version only runs demos for now and there is still a lot of work to be done on the GS and JIT compiler fronts for commercial games to be functional.

Going back to the thread's initial question, I will be making weekly builds available here: http://purei.org/downloads/play/weekly/

Only Windows for now, but I'm working on getting OSX and Android builds in there as well.

**Comment by destructorrph** [comment] 2015-03-23 02:44
Well thats awesome! I wish you good luck! Ill be stopping by to check it out! This really gives me hope for a mobile version of a PS2 emulator one day!

**Comment by Fadi5555** [comment] 2015-03-23 09:02
Jpd002 what about iOS port of it?
Please make it with your work like android and windows.
You know the most popular platform is iOS.

I leaved some comments up there but you didn't quote my comments.

Please do your best to make it.

**Comment by destructorrph** [comment] 2015-03-23 18:14
Android has a much higher marketshare than IOS, let alone jailbroken IOS
devices since you must jailbreak to play them.

http://www.businessinsider.com/iphone-v-android-market-share-2014-5

None the less i would support an IOS port once windows and android are
perfected.

**Comment by mantlebreath** [comment] 2015-03-23 19:34
@Fadi5555 Steps need to be taken first. It is just too much to handle to take on iOS, Windows, Mac, and Android, and possibly Linux as well, all at the same time. When the same JIT Android uses improves, it can also be worked into the iOS version later on. But first Android should be improved, along with possibly more stable versions for Windows and Mac with some improvements there too ... then iOS can be tackled in a more direct manner. These are just my thoughts though.

**Comment by Fadi5555** [comment] 2015-03-23 20:35
@mantlebreath. All I can say.
Thank you so much for replay. You can't imagine how I like this comment from you.
You're so kind. I'm grateful for all what you do about this project.
We're so exciting about this emu to arrive on our devices.

Please don't ignore ios port.
Like what happened with dolphin emu.
In that time it was our dream to run dolphin on our devices But unfortunately it didn't come until now. The creator of dolphin said if someone interested for ios port I'll help him for necessary things. But no one take it seriously. That's really so said.

For this one I believe on you. So i'm sure with your sharing knowledge and working together you'll get very good process on it.
So it well see the light with highly result. And beautiful compatibility.

Because it'll be much more portable because of your work on it.
So as I told you if you need something to test it on ios port I'm completely ready for that.

**Comment by jpd002** [comment] 2015-03-24 03:19
@Fadi5555 I'm definitively not closing the door to an official iOS build, but I'd like to get the ARM code generator and GLES GS handler to a level that will allow at least one commercial game to boot before starting the port.

**Comment by Fadi5555** [comment] 2015-03-24 13:48
@jpd002 I got the point. I completely with all what is you say.
But I just want from you is the ios port take the place beside android and windows in the weekly build to start the work and give report about it all the platforms in the same time. (Don't forget most of things on android looks like similar than ios, and jailbroken iOS devices have JIT as well)
I mean to save time just complete the builds on all platforms first including ios.
Then start to improve it all.
Like what they do on ppsspp. It's daily update (daily or weekly it's not the point) the point is to working with all.
This is my suggestion. I'm really hope to take my suggestion seriously and apply it.
I'm sure you will get the benefits of it because you start the work with it all and see and compare it between the different platforms to see and take and put it from here to there. Believe me. It will be easy to develop it all.

I really appreciate about all what you say and what you do with it. So i hope all the best for you to see your project the best ps2 emu ever for all platforms.

**Comment by vgturtle127** [comment] 2015-03-30 06:32
So the builds are all available HERE: http://purei.org/downloads/play/

That answers that question. :laughing: 

@Fadi5555 I thought Apple didn't allow JIT on their devices period? Also, maybe we should consider waiting until emulation is more complete for such a locked down platform? :confounded:

**Comment by Fadi5555** [comment] 2015-03-30 09:07
@vgturtle127 I got the point. And about JIT we can get it through jailbreak.
I think it's not a problem. Specially when get hard work on it.
We'll wait and see. I hope we get very good progress on all platforms.

**Comment by stodag** [comment] 2015-03-30 09:18
Not gonna happen on ios/android for at least another 5 years imo.. I struggle on pc.

**Comment by Fadi5555** [comment] 2015-03-30 11:42
Sorry i don't think so.
The creator @jpd002 doing his best bout his project. And get good progress on it. Including android port.
And put it on weekly updates. Now he try to develop it more for more stable and good progress. There is no impossible.
So we should wait for what will happen in near future.

**Comment by stodag** [comment] 2015-03-30 11:51
I never said it was impossible,  just not a playable experiance on mobile devices yet.. i could be wrong, he sure has got balls even takin on this task so nuff respect. ps2 is very hard to emulate so iv heard.

**Comment by jpd002** [comment] 2015-04-20 03:53
Closing this issue as question was answered and weekly builds are now available.

**Closed by jpd002** 2015-04-20 03:53 UTC
