### ISSUE TITLE
Futurama - Fry spins during gameplay

### ISSUE THREAD

**Issue by Souzooka** [jpd002/Play-#864] opened 2020-02-29 01:23 UTC
Revision 8078415F - When in game, Fry (the main player avatar) constantly spins.

https://cdn.discordapp.com/attachments/646159296589070397/683119588531109915/2020-02-28_20-12-34.mov

In DobieStation, we had debugged this recently, and had isolated two issues with the FPU which caused this. Likely Play! has one or both of these inaccurate behaviors.

1. When FPU arithmetic results in a denormal, the denormal is not flushed to 0. The game compares to see if 0 is less than 0x00200000 (result of 1 / FLT_MAX (clamped)) and if so, Fry will spin.

2. SQRT.S does not set the destination to -0 if the source is -0. If SQRT.S d, -0 results in d = 0, Fry will spin.

**Comment by Zer0xFF** [comment] 2020-03-11 10:45
Thanks for reporting, changes have been merged to master, if you can confirm the issue is fixed, you can close the issue.

**Comment by jpd002** [comment] 2020-03-11 13:18
Thanks for sharing that info with us @Souzooka.

Setting "denormals are zero" mode fixed the spinning issue for us. I'm not quite sure about the `SQRT.S` behavior, hardware tests seem to indicate the contrary: https://github.com/jpd002/ps2autotests/blob/master/tests/cpu/ee_fpu/sqrt.expected#L45

**Closed by jpd002** 2020-03-11 13:18 UTC
