### ISSUE TITLE
Odin Sphere: different compatibility between regions

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#590] opened 2017-06-29 05:10 UTC
The NTSC US/JP verision of Odin Sphere (SLUS_21577) runs very well, but the PAL version (SLES_55110) only boots to a black screen. It's an interesting bug because the engine is already running from one disc image.

I'm going to let @jpd002 or one of the developers change the name of the bug but if people want to report different compatibility I can put it all in a table

Game | JP | US | EUR
--|--|--|--
Castlevania: Curse of Darkness | works | | 
Odin Sphere | works | n/a |

**Comment by jpd002** [comment] 2017-07-04 13:45
Humm, weird, I'll take a look at the EU version. It might be looking for some specific stuff in `ROMVER`.

**Comment by literalmente-game** [comment] 2017-07-21 18:51
This is also true for Castlevania: Curse of Darkness. The JP region game boot and reach in-game, but the US version freeze

**Comment by jpd002** [comment] 2017-07-22 17:01
@literalmente-game You're getting a freeze after the intro movie on Castlevania: Curse of Darkness?

**Comment by literalmente-game** [comment] 2017-07-22 18:50
The game boot, I choose "New Game", and yeap, after the intro movie, freeze.

**Comment by jpd002** [comment] 2017-09-21 21:52
I tested the EU version of Odin Sphere and I can confirm that it's broken. Seems to be jumping to address 0 for some reason...

**Comment by jpd002** [comment] 2018-03-23 21:17
Odin Sphere EU should be working now. Was fixed by this: https://github.com/jpd002/Play-/commit/8767f70045e80c3385d42795b1935ee7cf208ff0
Probably related: https://github.com/jpd002/Play-/issues/607
Compatibility issue: https://github.com/jpd002/Play-Compatibility/issues/62
Also, the movies in Castlevania Curse of Darkness should be skippable now.

**Closed by jpd002** 2018-03-23 21:17 UTC
