### ISSUE TITLE
games testing-some results

### ISSUE THREAD

**Issue by bobbymc1985** [jpd002/Play-#78] opened 2015-07-06 18:20 UTC
Hi i dont know if anyone has got the same results.so far ive tested timesplitters, timesplitters 2 red faction and commandos 2. So far timesplitters 2 and commandos 2 do not load and have the black screen issue. Red faction loads up when you choose new game then it freezes with a black screen. Also timesplitters 1 freezes at the 1st loading screen. Hope these results help. Mite test others soon.

**Comment by MisterHubs** [comment] 2015-07-06 19:24
If you're just reporting game testing results, you can add them to the Wiki too:
https://github.com/jpd002/Play-/wiki/Compatible-games

**Comment by adriandennis17** [comment] 2015-07-08 18:21
the emulator is still in beta stage..and many games if not all won't run. depending on your device you might get to the intro and main menu if your using a high end device, if your using a low end device then black screen is very common..best to add your game test results to the wiki page.

**Comment by MisterHubs** [comment] 2015-07-08 18:46
@adriandennis17 I believe it's still "alpha," but even so there are more than 20 known games that are in-game on Android & I don't think high-end/low-end device matters with games working or not.

^This is only from about 60 or so games tested, and there are over 2,500 on PlayStation 2, I think.

I think the bigger thing is with the drivers and how they implement GL ES 3.0 maybe.

**Comment by adriandennis17** [comment] 2015-07-08 19:00
@MisterHubs High/Low ends device does matter games that some report with black screen i tested on my device and i actually got to in game..it's the same with PPSSPP and even though ppsspp has gone a far way in terms of development if your using a high end device some games will not run at 100% speed..

**Comment by MisterHubs** [comment] 2015-07-08 19:37
@adriandennis17 It would matter in terms of performance and future optimization potential maybe, but not in games showing black screens, as that has little to do with much besides the drivers and possibly the chipset and such. The driver would need to be good enough for the GL ES 3.0 stuff.

But we are getting off-topic here I think.

**Comment by adriandennis17** [comment] 2015-07-08 19:44
hmmm i get yah..and yeah getting a bit off-topic. peace ☆

**Comment by bobbymc1985** [comment] 2015-07-23 10:00
Just tested commandos strikeforce. It loads up past the pocketwatch loading screen then its a white screen after that.

**Comment by bobbymc1985** [comment] 2015-07-24 21:04
Also tested conflict desert storm,loads up to the first loading screen then white screen appears then freezes

**Comment by bobbymc1985** [comment] 2015-07-25 07:41
Conflict desert storm 2 crashes at sci games at the beginning.if anyone wants me to test certian games just comment and il see what i can do

**Comment by bobbymc1985** [comment] 2015-09-09 12:44
Ive downloaded the latest update with the black screen fix and im still getting black screen issues with some games. For example with timesplitters 2

**Comment by bigianb** [comment] 2015-09-09 13:53
There is not a generic 'black screen fix'. If anything goes wrong during the early stages of emulation and the game does not get to the stage where it is sending commands to the graphics processor then you will see a black screen. In this way, it is a common symptom that will have many causes. Fixing the cause for one game will most likely not fix other games (unless they use the same underlying game engine).

**Comment by jpd002** [comment] 2015-09-09 21:11
The "black screen fix" you are referring to was something that fixed games that were not showing anything on some Adreno-based Android devices but were working on other Android devices and PC. As @bigianb explained, many games are still unable to boot properly whether it's on PC or Android and it will take some time before they are fixed.

**Comment by literalmente-game** [comment] 2018-10-10 18:21
This issue can be closed as all the results for the tested games are moved to the compatibility tracker (https://github.com/jpd002/Play-Compatibility)

**Closed** 2018-10-10 21:10 UTC
