### ISSUE TITLE
[Feature Request] Ability to use bios

### ISSUE THREAD

**Issue by Spidy123222** [jpd002/Play-#1223] opened 2022-12-13 05:37 UTC
I would like to be able to have the boot menu and dashboard. So can enhance the experience (maybe even use whatever the bin has) and maybe manage memory card and internal ps2 settings. I use iOS and idk if other versions have it or not.

**Comment by eadmaster** [comment] 2023-04-25 23:15
duplicate of https://github.com/jpd002/Play-/issues/1074

**Comment by jpd002** [comment] 2024-02-19 17:58
Thanks for the request, but I have no plan to support this in the near future.

**Closed by jpd002** 2024-02-19 17:58 UTC
