### ISSUE TITLE
[iOS] Emulator crashes on game load

### ISSUE THREAD

**Issue by FourteenCoast** [jpd002/Play-#978] opened 2020-11-10 04:26 UTC
Tested with NTSC-U God Hand and NTSC-U Shin Megami Tensei: Nocturne

**Comment by ilovelinux** [comment] 2020-11-30 10:14
Both games doesn't work well on Play! but these issues should not lead to a crash.
Could you confirm that the issue is not the game that hangs but the iOS app that crashes?

**Comment by jpd002** [comment] 2021-02-10 14:33
@FourteenCoast Which version of iOS are you using? I'm assuming you are running on a non-jailbroken device with iOS 14? 

Going to close this one, since it's probably related to #1017.

**Closed by jpd002** 2021-02-10 14:33 UTC
