### ISSUE TITLE
Play! Android - screen brightness increase after using the analog gamepad controller

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#1130] opened 2021-10-05 06:01 UTC
## Issue Details
This issues happen when using the analog gamepad controller only. When using analog screen controller, it's not happen.

## Screenshots/Videos
Before using the analog gamepad controller
![Screenshot_20211004-230505](https://user-images.githubusercontent.com/55049420/135968667-e17da0ed-4b92-4842-bd97-52ddfdaa4254.jpg)

After using the analog gamepad controller.
![Screenshot_20211004-230523](https://user-images.githubusercontent.com/55049420/135968733-09cfa995-4404-4791-996c-f325bd09dbcf.jpg)

**Comment by jpd002** [comment] 2021-10-05 17:59
Duplicate of https://github.com/jpd002/Play-/issues/1089. Please comment there.

**Closed by jpd002** 2021-10-05 17:59 UTC
