### ISSUE TITLE
Gregory Horror Show crashes Play! instantly

### ISSUE THREAD

**Issue by ghost** [jpd002/Play-#62] opened 2015-06-19 06:05 UTC
This game has been proven to be quite the challenge to emulate, with PCSX2 still being unable to boot it or show anything for over six years since originally addressed. Would be impressive if someone could debug it in Play! and see the gist of why it won't work, and see if it could show anything eventually.

I think (not sure) it makes use of hardware quirks and the TLB, and PCSX2 as a LLE still has no hopes of running it in any way, patches or hacks or otherwise. It's sort of a cult-based title. 

I plan on debugging it myself soon, but thought I'd point this out to assure PCSX2's issues of booting some games due to problems long baked into the emulator can be avoided in Play! by identifying the bugs with the small section of games that PCSX2 can't run at all or needs heavy hacks/patches to do so.

I am in no way capable of fixing the issue of it crashing myself! But I can help with debugging at least, and I plan on attempting to do so soon (seeing as the only debugger is available on Windows).

**Comment by shakingboy** [comment] 2015-06-20 03:22
I can't seem to be able to get the debugger working. I downloaded the one from purei.org that says version 0.26, and everytime I try and load any ISO image of a PS2 game it just crashes. Am I doing something wrong? Does the debugger need dependencies I am not aware of?

**Comment by jpd002** [comment] 2015-06-20 03:50
Well, if it crashes right at the start, it might be hard to debug anything in the emulator's debugger. Are you able to build the emulator in VS2013? I'll probably start looking in handing off release builds with the debugger included so that everyone can debug.

Otherwise, I'll try getting the game, but it looks quite rare.

**Comment by shakingboy** [comment] 2015-06-26 17:40
Hm ... I am sort of confused on compiling Play! with the debugger. I checked the code after cloning locally and I notice there's the debug tools all part of the Windows UI itself. Is the debugger disabled on purpose in release builds that are in the weeklies? If so, I would need to manually compile everything or change project settings to include the debugger? Sorry, but I have never used Visual Studio before.

**Comment by jpd002** [comment] 2015-06-27 10:15
You can build a release with debugger version by changing the active configuration in Visual Studio:

![release_debugger](https://cloud.githubusercontent.com/assets/6760433/8391475/04a40304-1c93-11e5-8917-119d6ae0a1b3.png)

The debugger is not included in release builds because of it's overhead (nothing major, but still) and I need to do some changes before considering its inclusion in weekly builds. I'll see if I can provide a "release with debugger" build this Sunday at the same time I upload the new weekly version.

**Comment by jpd002** [comment] 2015-06-29 03:04
I've posted a debugger build along side today's weekly build : http://purei.org/downloads/play/weekly/PlayDebugger-20150628.exe . Just copy the file besides your emulator's installation in `C:\Program Files\Play\`.

**Comment by shakingboy** [comment] 2015-06-29 03:46
Yeah, I can barely get anything out of the debugger with Gregory Horror Show, but I caught a list of functions before it crashed and there's very little else that can be managed since it crashes instantly:
![functionseegregoryhorroshow](https://cloud.githubusercontent.com/assets/12419067/8400596/42d06cc8-1def-11e5-8651-31cd58e64f33.jpg)
And the ELF data, but that's about it:
![elfdata](https://cloud.githubusercontent.com/assets/12419067/8400612/8c2973f6-1def-11e5-9fc1-6eba1caf9cd6.jpg)

For me, at least, I still have absolutely no idea why it's crashing so quickly.

**Comment by jpd002** [comment] 2015-06-29 04:18
Well if it's crashing, the only way to figure it out would be running the emulator inside Visual Studio. You can try attaching Visual Studio's debugger to the emulator's process before booting the game to see where the crash is happening.

Otherwise, I will be getting the game this week or next week, so I should be able to fix the crash once I get it.

**Comment by shakingboy** [comment] 2015-06-29 04:24
Alright, getting a bit more now with a few cutarounds but not much else:

![iodis](https://cloud.githubusercontent.com/assets/12419067/8400947/0fadcec0-1df5-11e5-9e7f-c9eb52015563.jpg)
![callstack](https://cloud.githubusercontent.com/assets/12419067/8400948/10703c30-1df5-11e5-9870-a381a40e97f1.jpg)

I guess I'll give your method a try, but it's going to be a pain to setup this emulator and compile it.

**Comment by jpd002** [comment] 2015-07-03 02:34
Got the game today and after hacking in some things, I was able to get it to show something.

![gregory_1](https://cloud.githubusercontent.com/assets/6760433/8491590/1cf620a6-210a-11e5-9e26-41d7d045c8ce.jpg)
![gregory_2](https://cloud.githubusercontent.com/assets/6760433/8491589/1cf43b06-210a-11e5-9742-d3af64b08ce6.jpg)

Crash is caused by a weird transfer from IOP to EE through SIF that has a size > 0x80000000. Clamping the size fixes the crash. I'll see if I can push a branch with fixes later on.

**Comment by MisterHubs** [comment] 2015-07-10 00:55
Other games are in the same boat of not responding to input either, so perhaps any changes to the IOP would help games like Animaniacs: The Great Edgar Hunt, Destroy All Humans!, and some others that do boot but don't respond to any input for some reason. Will keep a close look on any IOP changes.

**Comment by jpd002** [comment] 2015-07-10 03:57
@MisterHubs Yeah, it's one of the biggest problems of the emulator right now. IOP HLE support is a bit flaky at the moment (thread scheduling is wrong, some missing kernel features, etc.)

**Comment by prafullpcsx2** [comment] 2015-07-12 21:13
@jpd002 fixes to this game have been merged yet? It still crashes for me.

**Comment by jpd002** [comment] 2015-07-13 03:02
I haven't merged the fixes in the master branch yet because there's some hacks in there. But here's the branch with the needed changes for the games: https://github.com/jpd002/Play-/tree/gregory

**Comment by ragekit** [comment] 2015-07-31 17:20
I'm really glad to hear that i might finally be able to play this game !
I tried compilling the gregory branch but i have no idea how to do it (i'm not really used to compilling stuff on a pc). Any ideas when a build with those changes will be available ?

**Comment by Fadi5555** [comment] 2015-07-31 19:52
We all hope of enhancing the compatibility of games.
Maybe if they could improve IOP a bit more than that it'll absolutely effects all games in a good way

**Comment by jpd002** [comment] 2015-10-04 02:21
I've been working on getting the game to work those past 2 days and here's the result:

![gregory_3](https://cloud.githubusercontent.com/assets/6760433/10266114/686d644e-6a1c-11e5-8f12-8514402381a3.jpg)
![gregory_4](https://cloud.githubusercontent.com/assets/6760433/10266115/6b336ec6-6a1c-11e5-9ef7-7b94782aa256.jpg)
![gregory_5](https://cloud.githubusercontent.com/assets/6760433/10266116/6ceff702-6a1c-11e5-9089-a7d864a559e4.jpg)
![gregory_6](https://cloud.githubusercontent.com/assets/6760433/10266117/6ea77ade-6a1c-11e5-9e2e-e3b108a041e5.jpg)
![gregory_7](https://cloud.githubusercontent.com/assets/6760433/10266118/70302c8e-6a1c-11e5-8117-4166f4d5ce58.jpg)
![gregory_8](https://cloud.githubusercontent.com/assets/6760433/10266119/718dc1f4-6a1c-11e5-8102-27f2b55d6ead.jpg)

I haven't played much, but everything seems to work well (except for the memory card). I might merge the changes needed for the game in tomorrow's build if they pass the tests.

**Comment by prafullpcsx2** [comment] 2015-10-04 04:27
Awesome stuff. :+1:

**Comment by Fadi5555** [comment] 2015-10-04 04:56
@jpd002 please see my thread about (Haunting ground).
It has the same thing on this game it' crash immediately when I select the game. Please fix that issue.
Thanks

**Comment by jpd002** [comment] 2015-10-05 02:17
Today's build got the changes needed to boot the game. It's only possible to play the game on Win32 though because I had to patch the executable to fix the input problem, but this is temporary and will be fixed soon (and it might fix other games too).

Closing this since the initial issue is now fixed.

**Closed by jpd002** 2015-10-05 02:17 UTC
Labels: bug

**Comment by johnnyleap** [comment] 2015-10-05 03:11
Perhaps it should be noted that this will only work for the Japanese version as of now, as the patch will not work for the European version. All versions no longer crash anymore and proceed to the language select screen, but input will only work for the Japanese version of the game. Just thought I'd clarify.

**Comment by jpd002** [comment] 2015-10-05 03:18
@johnnyleap Yes, that is right indeed. I'm planning to get rid of that patch ASAP and make sure both the japanese and european versions work properly.

**Comment by ADormant** [comment] 2015-10-08 17:51
https://github.com/jpd002/Play-/issues/62

**Comment by ADormant** [comment] 2015-10-08 17:53
https://github.com/PCSX2/pcsx2/issues/643

**Comment by jpd002** [comment] 2015-10-09 04:04
The controller issue is fixed: 80dd3c14eb5cc2b0ece67bf9afffb5d74b4bbf09. Patch is not needed anymore. It will be available in the next weekly build.
