### ISSUE TITLE
Gungrave: Player and NPCs clipped into ground

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#589] opened 2017-06-28 10:55 UTC
Gungrave is a good, old, and simple, third person shooter. Gets ingame but shows heaps of issues. Because it was released so close to launch we can assume it's a 3d title that's not using fancy programming tricks or weird effects so it's probably a good test candidate for fixing inaccuracies.

System: Sandy Bridge Core i7 with integrated HD3000 graphics, ubuntu 16.04
Version: commit b23f60f257a9bdd170489b6e2f7ada22917238e3
Disc: SLUS_20493

![screenshot from 2017-06-28 20 48 59](https://user-images.githubusercontent.com/20123543/27633644-61a16ee2-5c43-11e7-9a18-8eb75c92f4f7.png)

**Comment by paulaz2** [comment] 2017-07-03 23:48
Same problem with jet li rise to honour

**Comment by jpd002** [comment] 2017-07-04 13:48
Thanks for the report. I'll get the game, might be related to FP precision issues many games have.

**Comment by Nine-H** [comment] 2017-07-04 14:01
it's like everything is being transformed and translated around the wrong center point, even some of the 2d graphics on the menus, you'll see when you boot it. I don't mind filing the reports, I write a little code myself so I know broadly what to look for in a good bug: not too many moving parts, and visually debuggable.

**Comment by jpd002** [comment] 2017-08-26 01:48
Looks like it was caused by a missing instruction (namely `VMADDAq`), which I implemented in the [spongebob_movie](https://github.com/jpd002/Play-/tree/spongebob_movie) branch.

![capture](https://user-images.githubusercontent.com/6760433/29737622-02d77036-89df-11e7-8a45-3021748ebe05.PNG)

Never played that game before, but the controls seem a bit off. Guess there might be a bug there too?

**Comment by Nine-H** [comment] 2017-10-02 11:03
tested controls, in keyboard and on controller and yep, very broken.

**Comment by jpd002** [comment] 2018-03-31 22:05
Added a compatibility report for that game: https://github.com/jpd002/Play-Compatibility/issues/148. Closing this till we figure out the technical issue causing the problems.

**Closed by jpd002** 2018-03-31 22:05 UTC
