### ISSUE TITLE
Vulkan is supposed to work?

### ISSUE THREAD

**Issue by prafullpcsx2** [jpd002/Play-#859] opened 2020-02-23 18:45 UTC
I thought about testing vulkan mode on my 750Ti but whenever I select it the emulator closes automatically. Any special download required to get it working? I am using Windows 10 with 442.36 drivers

**Comment by Zer0xFF** [comment] 2020-02-26 13:44
while Vulkan is still being developed, the Vulkan render is usable.

I'm not entire sure how if nVidia has a the same level support of vulkan for all its drivers,
however assuming your using an apu (cpu with build in gpu) perhaps make sure your nvidia gpu is the one running `Play!`.

to add I'm not aware of any packaging dependencies for Vulkan.

**Comment by prafullpcsx2** [comment] 2020-02-26 13:48
No I am using dedicated GPU. GTX 750Ti. Although it's an older card but it does support vulkan and I can use vulkan in Rpcs3.

**Comment by Zer0xFF** [comment] 2020-02-26 14:03
I'm aware that 750Ti is a dedicated GPU.

Im suggesting that your CPU's GPU might be taking over, as `Play!` tries to use the 1st GPU it finds.

[this might article](https://www.addictivetips.com/windows-tips/force-app-to-use-dedicated-gpu-windows/) help in that regards

**Comment by prafullpcsx2** [comment] 2020-02-26 14:24
I am using 9100f cpu which doesn't have a GPU

**Comment by jpd002** [comment] 2020-02-26 14:43
There's probably something wrong in the Vulkan init code. I think it should work on your GTX 750 Ti.

Can you run this: http://vulkan.gpuinfo.org/download.php. Let us know if you have multiple GPUs in there and if your GTX 750 Ti has the fragment shader interlock extension?

![image](https://user-images.githubusercontent.com/6760433/75355280-3ebd3e00-587c-11ea-828a-44f0bef8ebcd.png)

Thanks!

**Comment by prafullpcsx2** [comment] 2020-02-26 15:02
I ran the tool and my GTX 750 Ti doesn't have the fragment shader interlock extension. I guess that means I won't be able to use vulkan with play ?

**Comment by mrcmunir** [comment] 2020-02-26 19:11
fragment_shader_interlock seems only supported on Nvidia 900 series or newer GPUs

**Comment by boberto5888** [comment] 2020-02-27 20:28
> fragment_shader_interlock seems only supported on Nvidia 900 series or newer GPUs

Really, that's odd because the gpu_gs_ram and sw_buffer_emulation branches <sup>(shader interlock on OpenGL)</sup> work on my GTX 480.

The extension isn't listed by glcapsviewer though.

**Comment by KingDuckZ** [comment] 2020-03-18 16:06
I can confirm selecting Vulkan just causes a segfault. My laptop has an integrated GPU:

> VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev d0)

I'm sure Vulkan generally works, it may be lacking some required extensions, that I'm not sure. I don't get any message printed to stdout, just a good old segfault.

**Comment by DragonSWDev** [comment] 2020-03-31 15:00
It crashes for me as well. I'm running Arch Linux and my GPU is Radeon RX570. I'm using latest AppImage downloaded from site and Play! crashes with segfault when I choose Vulkan in settings. Emulator itself works in OpenGL mode.

**Comment by Zer0xFF** [comment] 2020-03-31 15:03
AMD gpu's not supported by vulkan render, as they dont support interlocking shaders extension

**Comment by weter11** [comment] 2020-04-02 19:25
Ubuntu Linux. Notebook have "Optimus" system (UHD620+MX150). Usually in other emulators I need to choose Vulkan device, libvulkan.so.1 installed. Without libvulkan-dev such error:
`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2632, resource id: 10442150, major code: 40 (TranslateCoords), minor code: 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load Vulkan library: libvulkan.so`
Is it normal that it need libvulkan-dev intead of libvulkan1?

**Comment by weter11** [comment] 2020-04-22 21:33
Little update. It looked for libvulkan.so, not for symlink libvulkan.so.1. So, I copy library and put it with name libvulkan.so to the same folder and now no more messages with error. But when I try to choose Vulkan emulator crash.
Vulkan working only under Win systems at this moment?

**Comment by jpd002** [comment] 2020-04-23 15:18
Hi @weter11, I think it should work with your UHD620 at least. There's probably something wrong with the way I load Vulkan on Linux, I'll look into it.

**Comment by jpd002** [comment] 2020-04-29 14:55
Hello all, I just merged changes to make Vulkan device handling a bit more error proof:
- Now, if no suitable Vulkan device is available, Vulkan won't be usable as an option. 
- If you have more than one suitable device, you should be able to choose the device you want to use. 
- There's also a new "Vulkan Device Info" button in the settings that will show you the details of the device selection.

I'm going to close this, but feel free to reopen or comment if you have questions/issues.

**Closed by jpd002** 2020-04-29 14:55 UTC
