### ISSUE TITLE
Graphical issues with Lego games

### ISSUE THREAD

**Issue by bigianb** [jpd002/Play-#571] opened 2017-05-20 20:48 UTC
The Lego games (star wars and batman are the ones I have tested) have graphical issues. It looks like some of the vertices get very large numbers in them ... so I suspect some an issue with how numeric exceptions are handled.
I'll take a dig, but any hints as to where to look would be appreciated.

**Comment by jpd002** [comment] 2017-05-22 03:09
I'd try placing `ClampVector` calls in FMAC operations ([example](https://github.com/jpd002/Play-/blob/25e817802a96d2683bf266b200ad507f80aed6d6/Source/ee/VUShared.cpp#L314)) to see if that changes anything.

Also, some games have spiky meshes issues because FMAC stalls are not emulated. Playing with `LATENCY_DIV` might do something ([link](https://github.com/jpd002/Play-/blob/25e817802a96d2683bf266b200ad507f80aed6d6/Source/ee/VUShared.cpp#L9)).

**Comment by iOS4all** [comment] 2017-05-22 09:51
Maybe it's same issue on crash bandicoot the warth of cortex. It has graphical issues. Maybe if this game fixed it will effect to this game as well.

**Comment by bigianb** [comment] 2017-05-25 20:41
found some time to investigate - setting LATENCY_DIV to 6 seems to resolve the issue. Adding the clamps had no effect. I guess we need to isolate the code that's failing and hook it into a test case and figure out what the latency should really be (I've not even looked at what this constant does yet :))

**Comment by jpd002** [comment] 2017-05-26 04:04
Would be interesting to test with that branch to see if the problem is fixed: https://github.com/jpd002/Play-/tree/fmac_hazard. There's a [FMAC hazard detector](https://github.com/jpd002/Play-/commit/7e00ed84621cf8de34c1eb1481e46694fc08e8c1#diff-d59f2ea71d55d6da284a9da752164550R143) in that branch which should detect the hazard if there's one.

That branch wasn't merged because it breaks more games than it fixes. I haven't really looked into improving it further yet.

**Comment by bigianb** [comment] 2017-05-26 21:52
I had a quick look at the branch but the cmake build fails because IUUC is not found. Can you merge the latest head into it (I think some recent cmake changes fix that issue) and then I'll take a look.

**Comment by jpd002** [comment] 2017-05-27 03:10
Rebased the branch.

The thing with FMAC stalls is that other units (FDIV, EFU) will continue to operate when the FMAC is stalled. 

When there's no stall, the result for a `DIV` operation will be available after 7 "instructions" (LATENCY_DIV).

When there's a stall, the result for a `DIV` operation will be available "earlier" because the stalled instruction will take 1 or more cycles than usual to complete.

Example of this [here](https://github.com/unknownbrackets/ps2autotests/blob/master/tests/vu/lower/fdivdelay.cpp#L216). In that test, the `CLIP` instruction can stall because it's waiting for the result from the previous `MADD` instruction. The result from `DIV` will appear "earlier" because of that.

**Comment by bigianb** [comment] 2017-05-30 22:38
The fmac branch does not fix the issue ... so I guess it does not detect the hazard.

On a different but related note though, I notice that this assertion is thrown which presumably would affect rendering:

Program: C:\emu\play\play\build_cmake\build\Debug\Play.exe
File: C:\emu\play\play\Source\gs\GSH_OpenGL\GSH_OpenGL.cpp
Line: 1512

Expression: (m_vertexBuffer.size() + 3) <= VERTEX_BUFFER_SIZE

m_vertexBuffer.size() is 0x10bf in the debugger and VERTEX_BUFFER_SIZE is 0x1000

**Comment by bigianb** [comment] 2017-06-02 22:09
I've been looking at your fmac branch. I wonder if the issue is that the waitq instruction or queued DIV instructions do not increment the relative pipeline. I would think that VUShared::FlushPipeline would need to return the number of pipeline cycles it stalled for so that relativePipeline could be adjusted.

**Comment by boberto5888** [comment] 2019-01-04 23:05
FMAC hazard detection seems to have improved with the merge of the [block_lookup branch](https://github.com/jpd002/Play-/compare/525dfae51e57...a68cf01d0905)?

Anyway, fmac_hazard branch now properly detects the hazards and prevents exploding vertices in Lego Batman and Lego Star Wars.

**Comment by bigianb** [comment] 2019-01-08 23:44
Just tested lego batman and the vertices still look bad

**Comment by boberto5888** [comment] 2019-01-10 04:34
@bigianb You should be testing on fmac_hazard branch, not master. Sorry for the confusion.

**Comment by jpd002** [comment] 2021-12-05 20:21
That's been fixed for a while. Closing.

**Closed by jpd002** 2021-12-05 20:21 UTC
