### ISSUE TITLE
[Request] Add Vulkan Feature For Play! Mobile Versions

### ISSUE THREAD

**Issue by ericsonia** [jpd002/Play-#847] opened 2020-02-04 15:07 UTC
![Screenshot_2020-02-04_220422](https://user-images.githubusercontent.com/55049420/73756749-af4fce00-479a-11ea-87ea-7d9c82f7833e.jpg)
:)

**Comment by Dragon20C** [comment] 2020-02-04 22:10
where is this from, what is this? and vulkan has been in the works for a few months now

**Comment by ericsonia** [comment] 2020-02-05 02:33
> where is this from, what is this? and vulkan has been in the works for a few months now

https://youtu.be/O0_ARU7RyfE

**Comment by Spidy123222** [comment] 2020-05-24 20:22
> ![Screenshot_2020-02-04_220422](https://user-images.githubusercontent.com/55049420/73756749-af4fce00-479a-11ea-87ea-7d9c82f7833e.jpg)
> 
> :)

Do you think you should add for iOS also. iOS supports Vulkan also but needs a thing called moltenVK. Reason I don’t make a separate post for it because it would just be a duplicate of this post but for iOS.

On their discord they said that OpenGL performs better Wich I disagree with proof from your video. iOS doesn’t update open gl anymore and uses metal. A emulator called Dolphinios is on iOS and their OpenGL runs so bad that they recommend only to use Vulkan even tho it’s extremely optimized. Vulkan performs better on iOS because metal is Vulkan with different stuff.

**Comment by GuilhermeGS2** [comment] 2021-01-05 17:07
Don't expect the same kind of improvement on Android, the mobile drivers are poorly optimized and sometimes Vulkan can be worse than OpenGL. On PPSSPP and Dolphin I have better performance using OpenGL.

**Comment by jpd002** [comment] 2021-04-15 14:44
Maybe there will be support for Vulkan on mobile at some point, but for now OpenGL is still the best option for mobile.

Also, the Vulkan GS handler uses a render technique which is probably not totally compatible with the way mobile GPUs work. I'm having hope with the Apple M1 chip that maybe mobile GPUs will move towards something more friendly to that render technique. Time will tell.

**Comment by jpd002** [comment] 2021-06-24 12:37
After some experimentation, it seems Vulkan on mobile is not too far off.

I was playing around trying to fix some nasty bugs only happening on Apple M1 on Vulkan when I realized the GPU on that chip is very close to what is available on mobile devices. I'm working on an alternate Vulkan path for tiled GPUs to fix these bugs (ideas that came from all the tests we did with frame buffer fetch on OpenGL) that will hopefully work, but meanwhile, I decided to try the current Vulkan path on my iPhone 11.

And it seems to work fine! With the same bugs that the Apple M1 has. Performance is good too which is really surprising considering the unorthodox pipeline. If anyone wants to try, you can fetch the build from that branch: https://github.com/jpd002/Play-/tree/vulkan_ios.

I'll check how I can make it work on Android next, but I'm pretty sure it'll require the new tiled GPU path since no Android device has fragment shader interlock.

**Comment by Gamemulatorer** [comment] 2021-06-24 16:03
> 
> I'll check how I can make it work on Android next, but I'm pretty sure it'll require the new tiled GPU path since no Android device has fragment shader interlock.

Nice I'm very excited and I can't wait to test it on my Redmi Note 9 🎉😁

**Comment by Spidy123222** [comment] 2021-06-24 19:47
> After some experimentation, it seems Vulkan on mobile is not too far off.
> 
> 
> 
> I was playing around trying to fix some nasty bugs only happening on Apple M1 on Vulkan when I realized the GPU on that chip is very close to what is available on mobile devices. I'm working on an alternate Vulkan path for tiled GPUs to fix these bugs (ideas that came from all the tests we did with frame buffer fetch on OpenGL) that will hopefully work, but meanwhile, I decided to try the current Vulkan path on my iPhone 11.
> 
> 
> 
> And it seems to work fine! With the same bugs that the Apple M1 has. Performance is good too which is really surprising considering the unorthodox pipeline. If anyone wants to try, you can fetch the build from that branch: https://github.com/jpd002/Play-/tree/vulkan_ios.
> 
> 
> 
> I'll check how I can make it work on Android next, but I'm pretty sure it'll require the new tiled GPU path since no Android device has fragment shader interlock.

Looks like I get pretty good gains in fps in battle for bikini bottom. Great work in this improvement. 

By the way I talk to DolphinIOS devs a lot and they seem to get better performance when they downgraded moltenVK to 1.2.135 do you think you can do a build for that I don't have Xcode to compile it unless there's a way without a Mac.

**Comment by Githubot1957** [comment] 2021-07-14 02:35
@jpd002 this latest commit https://github.com/jpd002/Play-/commit/e9bc72281053a338922a1f220e4a6323239acd1a is   vulkan default on android?

**Comment by ericsonia** [comment] 2021-07-14 07:34
> @jpd002 this latest commit [e9bc722](https://github.com/jpd002/Play-/commit/e9bc72281053a338922a1f220e4a6323239acd1a) is vulkan default on android?

@Githubot1957 nope
![Screenshot_20210714-143220891_1](https://user-images.githubusercontent.com/55049420/125581921-35af5a7e-21ff-49f6-a1fa-426b5feff5af.jpg)

**Comment by Gamemulatorer** [comment] 2021-09-30 16:25
This feature request can be closed now, Play! PS2 emulator now support vulkan on mobile 🎉🎊
![Screenshot_2021-10-01-00-24-24-988_com virtualapplications play](https://user-images.githubusercontent.com/37603562/135494134-3efb22a7-c18f-41c7-8633-2d77014c76fa.jpg)

**Closed** 2021-10-01 00:05 UTC
