### ISSUE TITLE
Memory Card Issues

### ISSUE THREAD

**Issue by Nine-H** [jpd002/Play-#638] opened 2017-10-02 11:01 UTC
I've noticed some games that can't read memory cards in Play! and some that hang while trying to read them, for example:

Yakuza, Katamari Damaci: can't read memory card, shows play anyway screen
We Love Katamari: hangs on access memory card screen

I'm wondering if more games would get to the main menu if memory card bugs were looked at.

**Comment by atomic83GitHub** [comment] 2018-01-11 09:33
Hum, probably related to this: https://github.com/jpd002/Play-/issues/620

**Comment by jpd002** [comment] 2018-03-19 23:24
Thanks for reporting the issues. I've created a issue label that will help us track games that have memory card issues: https://github.com/jpd002/Play-Compatibility/issues?q=is%3Aissue+is%3Aopen+label%3Aissue-memorycard

Feel free to add the other games to the tracker (I don't have the game ids handy).

**Comment by Nine-H** [comment] 2018-04-06 11:05
no wackas, I like your project can you add me to the QA compatibility team?

**Comment by atomic83GitHub** [comment] 2018-05-18 19:06
This can be close I think.

**Comment by unknownbrackets** [comment] 2019-06-07 01:46
I may be wrong, but at least in jpd002/Play-Compatibility#868, I think it's calling sio2man, which is ultimately using IOP SIO2 DMA that is being ignored.

It does seem like sio2man is meant to be mapped to CPadMan, but it's instead using CDynamic from `RegisterLibraryEntries` being called.  But also, CPadMan is not prepared to handle memory card related calls.

AFAICT it loads sio2man, compressed (LZR), from a data file on the iso.  It doesn't seem to pass through LoadModule.

PCSX2 handles the IOP DMA which is how the same game is able to save properly there: https://github.com/PCSX2/pcsx2/search?utf8=%E2%9C%93&q=HW_SIO_DATA

-[Unknown]

**Comment by jpd002** [comment] 2019-06-07 18:00
In the case of Mana Khemia (and more recent Gust games), they are indeed using a different version of libmc which the emulator doesn't support.

I've debugged it real quick, I haven't seen accesses to 0x1F801040 (the SIO port). SIO2 is emulated for controllers, but it doesn't go through CPadMan (PadMan is only used for homebrew stuff). I'll dig a bit more to see what's going on.

**Comment by unknownbrackets** [comment] 2019-06-08 05:37
I initially saw the actual SIO2 access in PCSX2, as sio2man -> dmacman -> [DMA write](https://github.com/PCSX2/pcsx2/blob/d05163a26f7382398f733c13471d6bbaad4890cc/pcsx2/IopSio2.cpp#L226).

The trace looks like sio2d -> sio2man -> dmacman_unknown_001C / 0020.  In Play, stepping never goes into dmacman, but it does in PCSX2 (bounces around a bit in dmacman.)

It hits `Hack: PS2 IOP uses ADDIU R0, R0, $x for dynamic linking` for dmacman, but then follows the `Trying to call a function from non-existing module ` path.  `RegisterLibraryEntries` is not called for `dmacman`.

As far as I can tell, in PCSX2 it comes from the BIOS, same as thsemap, timrman, sifman, intrman, excepman, etc.  So I guess ultimately this is caused by (in Khemia, at least) missing dmacman HLE?

Also, a friendly nitpick: looking at e.g. `CIntrman::GetFunctionName` shows careful use of consts for the strings (likely to be obvious if wrong), but no constants for the magic function numbers (feels like I'd never notice if `CIntrman::Invoke` had a typo.)  Seems backwards.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-09-06 23:30
As noted in https://github.com/jpd002/Play-Compatibility/issues/868, this may be fixed now.

-[Unknown]

**Closed** 2021-11-29 14:20 UTC

**Comment by jpd002** [comment] 2021-11-29 14:21
LibMc2 HLE has been available for a while. Should help a lot with many games, please report game specific issues in the compatibility tracker.
