### ISSUE TITLE
fatal frame 2 boots again

### ISSUE THREAD

**Issue by spring568** [jpd002/Play-#607] opened 2017-08-10 19:35 UTC
Using the GT4 branch. You can actually get in game too if you load up a save except only the 2D UI works. The post processing effect covers all the 3d stuff. This isn't an issue per say but just being informative. You also couldn't even get in game before loading a save so that's new

**Comment by jpd002** [comment] 2017-08-11 14:11
Nice! The GT4 branch still needs some work before it can be merged. It prevents some other games from booting and causes weird issues in others because it changes the way interrupts are handled. Maybe there's a specific commit that fixes the issue with Fatal Frame 2 that could be brought in master without breaking other games.

**Comment by spring568** [comment] 2017-08-11 22:06
I'll see if I can figure it out which commit it is, but I'm not very good at doing it either. Tried doing the same thing with rpcs3

**Comment by jpd002** [comment] 2017-08-23 14:37
I've created a branch with the commit which I think fixes the issue: https://github.com/jpd002/Play-/tree/spu_throttle

**Comment by spring568** [comment] 2017-08-30 19:31
Woah, thanks so much for checking. Sadly that doesn't fix it at all. I really need to find some time to do this properly

**Comment by jpd002** [comment] 2017-08-30 19:35
I've found out why that branch was causing other games to act up. If all tests pass, I will merge it in master shortly.

**Comment by spring568** [comment] 2017-08-31 03:58
Sounds good! If it passes I'll give it a try again once you merge

**Comment by atomic83GitHub** [comment] 2018-01-11 08:29
Any status on this branch?

**Comment by jpd002** [comment] 2018-03-23 21:08
Pretty sure 8767f70045e80c3385d42795b1935ee7cf208ff0 was the commit that made that game run again. It was the reason the EU version of Odin Sphere was broken. The [latest build](https://s3.us-east-2.amazonaws.com/playbuilds/6f60107a/Play-0.30-64.exe) on master has that commit in, could you try the game with that build? Thanks!

**Comment by jpd002** [comment] 2018-03-31 20:18
Game booting was confirmed: https://github.com/jpd002/Play-Compatibility/issues/125.

Still not playable for now though. Closing till we figure out the technical issue behind that.

**Closed by jpd002** 2018-03-31 20:18 UTC

**Comment by spring568** [comment] 2018-04-09 09:58
Wow sorry about that. Yeah the UI shows up, but you can't really see anything in game. If you snap a photo with the camera obscura it'll actually show the level

**Comment by jpd002** [comment] 2018-04-09 15:46
No worries, thanks for the update!! I'll copy the screen shots in the compatibility tracker!

**Comment by spring568** [comment] 2018-04-09 21:27
Thank you very much! That save I used was near the end of the game even.  The game runs really well too at least in that one spot I tried. I don't like horror games that much, but I always liked fatal frame 2
