### ISSUE TITLE
Phantasy Star Generation 2 crash

### ISSUE THREAD

**Issue by DeIVloN** [jpd002/Play-#579] opened 2017-06-19 11:09 UTC
Hello. Download Play, PSG2 iso and try to launch. Loading was good, get start screen. But this is all, when I push to start, game crash and go back to Play menu.
![s70619-16094019](https://user-images.githubusercontent.com/29541551/27282466-88057146-5509-11e7-9375-75cdfe3e1044.jpg)

**Comment by jpd002** [comment] 2017-06-20 02:51
It crashes every single time you press start? Which device are you playing on?

**Comment by DeIVloN** [comment] 2017-06-20 03:32
Yes, every time when push start i getting crash, no one times i don't pass this moment. If u choose Continue, u get load screen where u can choose slot of save  data, which i haven't. Last options Original game also crash, but a little longer, before u see black screen for a few sec. On PC version ISO was good, reason not in it. My device Meizu MX4, Android 5.1 Flyme.

P.S. This is load screen of save data. I can write link on ISO, i don't do it before cuz i don't know rules about it.
![s70620-083309](https://user-images.githubusercontent.com/29541551/27315421-ec098b9e-5592-11e7-95c5-829d7c70616e.jpg)

**Comment by DeIVloN** [comment] 2017-07-13 11:00
Start test on ver. at 09.07.2017 - same result.

**Comment by einhander** [comment] 2017-08-31 19:37
Just tested this game on xiaomi redmi note 3 MTK using 2017\8\29 build. No crush at all. Game runs at 15 fps in town and 60fps in dialogs.
Main issue is screen flickering or shaking.

**Comment by jpd002** [comment] 2017-08-31 20:01
I tried both the original and translated versions and I couldn't reproduce the issue. But, it's possible that this [commit](https://github.com/jpd002/Play--CodeGen/commit/f5a8055bdc0e677b4fcf5d2bbd963af91a001f7c), which was released in the 2017-08-29 build, fixed the issue. The missing table terminator might have caused random crashes.

**Comment by jpd002** [comment] 2018-04-24 21:47
Going to close this for now since there's no activity. There has been other fixes to code generation that might fix that issue, so, it might be interesting to test with the latest [automated build ](http://purei.org/downloads.php) on your device to see if it's any better now.

**Closed by jpd002** 2018-04-24 21:47 UTC
