### ISSUE TITLE
gta san andreas free fall forever after loading savegame

### ISSUE THREAD

**Issue by annahana** [jpd002/Play-#331] opened 2015-10-07 08:38 UTC
system windows 7 pro x64
gpu amd radeon hd 6450
cpu intel core i3 2120 
ram 4 gb

last weekly build

if i load a savegame, cj will fall through the floor of the house and will fall forever.

**Comment by johnnyleap** [comment] 2015-10-07 22:25
Sounds vaguely similar to [Jet Li: Rise to Honor's issue](https://github.com/jpd002/Play-/issues/69#issuecomment-120572661).

Unfortunately, I have no idea what the problem could be, so I can't even comment on why it's happening or how it may be fixed/etc. @jpd002 might know what the problem(s) are caused by though.

**Comment by jpd002** [comment] 2015-10-08 02:45
Yeah, it might be the same problem. My guess is that those games are using VU flags for detection collision and VU flags aren't properly set in VU macro mode at the moment. I know other games that exhibit the same issue, namely, Mark of Kri and Samurai Legend Musashi. 

Fixing this problem is on my TODO list.

**Comment by annahana** [comment] 2015-10-12 11:18
video how it lock in latest weakly build 
https://www.facebook.com/anna.hana.33/videos/934852946586698/?l=8663774946856748388

**Comment by jpd002** [comment] 2015-12-10 05:19
Just to add to this, True Crime LA also has an issue with VU flags not being handled properly in macro mode. Fixing flags is getting higher in priority.

**Comment by jpd002** [comment] 2017-08-09 17:54
Closing this as the free falling issue was fixed. The game still exhibits severe graphical issues though.

**Closed by jpd002** 2017-08-09 17:54 UTC
Labels: bug
