### ISSUE TITLE
Rpi 4 build of Play error when loading a game

### ISSUE THREAD

**Issue by namanix** [jpd002/Play-#769] opened 2019-07-02 13:34 UTC
Hi there,

To test out the performance of the new Rpi4 I've compiled a version of Play for RetroArch (1.7.7) onto it. But every time I load a game I get the following error:
```
PS2VM: Error mounting cdrom0 device: Invalid file handle.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No 'SYSTEM.CNF' file found on the cdrom0 device.
Aborted
```
It's build with: cmake .. -DBUILD_LIBRETRO_CORE=ON -DBUILD_PLAY=OFF 

We tested a lot of things in discord. But nothing helped.
Made a cso file to make the file smaller than 4gb because it's a 32bit OS.

The iso was tested on Android and Windows. Both seem to work.

This is all done on the newest Raspbian OS - Buster

**Comment by Zer0xFF** [comment] 2019-07-06 16:10
this was caused by `fopen` on 32bit linux system not being able to open files greater than 2GB, the options where, to use `fopen64`, which is none standard and would also involve changing other calls to their 64 bit version, but they might not exist, or use `add_definitions(-D_FILE_OFFSET_BITS=64)` which while is also non standard, meant the code can compile regardless of whether there is support or not.

the fix should probably be applied in `Framework` and defined as a public definition to propagate the rest of the project.

this can be closed once the solution is merged.

**Comment by Zer0xFF** [comment] 2019-11-23 00:45
Can be closed.

**Closed** 2019-11-23 01:38 UTC
