### ISSUE TITLE
(iOS) "Crash Bandicoot: The Wrath of Cortex" crash results

### ISSUE THREAD

**Issue by Keyaku** [jpd002/Play-#482] opened 2016-10-17 01:21 UTC
By running Play! on a iOS device (iPhone 6), I can see that the emulator "gives up" when the console outputs `MipsExecutor: Warning. Found no JR after a big distance`.

However, this doesn't crash the emulator. These, on the other hand, do:

**Crash n.1**
Select "Load Game" and step over a level in the Warp Room. Play! crashes at [GSHandler.cpp:735](https://github.com/jpd002/Play-/blob/master/Source/gs/GSHandler.cpp#L735), with the error `EXC_BAD_ACCESS`.

**Crash n.2**
Select "New Game", input name, wait for the Loading screen to fade. Play! crashes at [GSHandler.cpp:735](https://github.com/jpd002/Play-/blob/master/Source/gs/GSHandler.cpp#L735), with the error `EXC_BAD_ACCESS`.

`pSrc` is `NULL` in this instance, which explains the crash (no pun intended. OK, pun _definitely_ intended).

Backtracing gives:
* [GSHandler.cpp::TransferWriteHandlerPSMCT24::735](https://github.com/jpd002/Play-/blob/master/Source/gs/GSHandler.cpp#L735)
* [GSHandler.cpp::FeedImageDataImpl::556](https://github.com/jpd002/Play-/blob/master/Source/gs/GSHandler.cpp#L556)

Just thought I could add this info here. Will update this issue when I further study the project and tinker with the code a bit.

**Comment by jpd002** [comment] 2016-10-18 02:47
Interesting, thanks for the details. I was able to reproduce it on my side, not quite sure about the cause of the problem yet (could it be a memory allocation failure returning null?).

**Comment by jpd002** [comment] 2016-10-20 02:25
Ok, that line of code is a bit naughty: https://github.com/jpd002/Play-/blob/master/Source/gs/GSHandler.cpp#L735. It's going to read 1 byte past the bounds of the incoming data stream at the end because it's reading an `uint32` (4 bytes) at every step even though it only uses 3 of those bytes.

So, I've made the data stream a bit bigger to prevent the crash: https://github.com/jpd002/Play-/commit/69dc2ca87aa9bbd27271654ceb8694237b5e15c1

**Comment by Fadi5555** [comment] 2016-10-20 05:14
The latest build I got crash bandicoot the warth of correx show something.
Unfortunately it's only on load screen and never passed.
This is image of the game on my iPad Air 2:
![image](https://cloud.githubusercontent.com/assets/10546081/19547024/1ed08f10-969d-11e6-92c7-e8bebe081237.png)

For more information this is my own thread about this game:
https://github.com/jpd002/Play-/issues/363

**Comment by jpd002** [comment] 2016-10-21 03:26
@Fadi5555 He's testing on a build he made himself. The game is playable on master. I'll make a new build soon.

**Comment by Fadi5555** [comment] 2016-10-21 12:18
@jpd002 Oh thank you so much I wa waiting for this game to be playable for long time. Another thing. Please could you please add start and select buttons to Ps3/4 controllers? All the buttons working great except start and select it's not mapping yet.

Anyway I'm waiting for the new bulid patiently.

My last advice is try to attract some devs who familiar with this things. I mean to continue your amazing work. Because most of the time you're not here (I know because of your real life)
Just see projects like ppsspp and retroarch and even dolphin there are many people who help each other and working on that regularly. I hope you could find any solution to get more people who really interesting to work with.
To keep this amazing project up.

**Comment by Keyaku** [comment] 2016-10-21 14:14
Sorry for the late reply, I had a really busy week.

> I've made the data stream a bit bigger to prevent the crash: 69dc2ca.

Just tested, and wow: not only did it clean the `MipsExecuter` warning, it now corrects every crash related to this one line (cutscenes, stepping on levels, etc…), so that part is fixed.

If this change does not bring any new assortment of problems, I'd merge this to master and close this issue!

**Comment by jpd002** [comment] 2016-10-22 03:16
Thanks for testing. The change is pretty harmless, I've merged it in master.

**Closed by jpd002** 2016-10-22 03:16 UTC
