### ISSUE TITLE
Kingdom Hearts 2 lag

### ISSUE THREAD

**Issue by edwardmx96** [jpd002/Play-#53] opened 2015-05-26 00:39 UTC
Hey, I started testing your PS2 emulator the other day. I tried playing Kingdom Hearts 2 and noticed it lags a lot before reaching the title screen. I am using the Nvidia Shield Tablet if that helps. Btw, thank you for making PS2 emulation possible on android devices. I am looking forward to your future releases.

**Comment by gambrio** [comment] 2015-05-26 02:16
All games are relatively slow (some more than others, and it depends on the device too), and it's a combination of factors, namely the renderer/OpenGL overhead and more overall optimization needed.

This is what Kingdom Hearts 1 looks like at the title screen (only takes a few seconds to get there on the Xiaomi Mipad for me, and it seems to show on half of the screen for some reason):
![100_0887](https://cloud.githubusercontent.com/assets/12025386/7804048/fea32330-032a-11e5-862c-4978a2956663.JPG)

But when you select new game (hard to see with somewhat messed up graphics), the first FMV looks like:
![100_0885](https://cloud.githubusercontent.com/assets/12025386/7804060/21e45bf2-032b-11e5-943d-868a332a7d2d.JPG)

But waiting for 40 minutes and it never passes it (don't know if it ever does or doesn't, as it could just be extremely slow and you can hardly tell what's being shown while Play! is rendering the FMV).

Since all games are not created equal, some will always be noticeably faster/slower on certain devices.

**Comment by edwardmx96** [comment] 2015-05-26 02:27
I get half screen as well on Kingdom Hearts 2. I agree though. I noticed how Kingdom Hearts 1 and 2 differ on emulation. For the lag, on Kingdom Hearts 2, I got probably one frame for every second, then it would stay frozen on a blank screen before the title screen even shows. I will upload screenshots. Do you think it could be device drivers being the reason for lag? I have the same Tetra K1 processor.

**Comment by gambrio** [comment] 2015-05-26 02:35
Drivers can make a difference, but I doubt it's much of a deal between mine and your case; in other words, it's probably the game and how the emulator is handling it and not necessarily the driver being a big deal.

BUT ... I think @jpd002 can likely give much better input than I can about some of the minor rendering faults.

**Comment by edwardmx96** [comment] 2015-05-26 02:42
Yeah, but I am pretty sure that once the "Play!" emulator is near completion, Tegra K1 devices will have no problem running it.

**Comment by jpd002** [comment] 2015-05-26 03:28
The half screen issue is due to mishandling of interlaced mode in GLES mode. This should be fixed in next weekly.

I got KH to run up to the first "scene" (where Sora is in the inside world), but it does take a long time to get there (I didn't time it, but it's easily 10+ minutes). The green stuff is indeed the FMV playing. I haven't tried, but it would probably be possible to use some saved games to see some actual gameplay action faster.

I didn't try KH2 on Android yet, but I did try it on PC and it's slow there too. I haven't investigated the issue yet, but it might be caused by a speed hack not kicking in properly (there's no reason for the logo screens to be slow).

**Comment by gambrio** [comment] 2015-05-26 04:04
@jpd002 I was actually going to do the memory card, saved game bit, but Play! doesn't seem to support the save format of PCSX2 memory cards to carry over data to test. Could you explain the format/differences?

I was thinking of converting the files to test and do just that with KH and maybe FFX.

**Comment by jpd002** [comment] 2015-05-26 05:00
@gambrio Humm, I've never had a look at PCSX2's memory card format, but I guess they store memory card data in a huge blob. Play! stores all the files individually inside a mc0 or mc1 folder which is found inside the "Play! Data Files" folder (usually in My Documents).

The memory card manager from the Win32 version is able to import files from Sharkport or Action Replay save dumps. It should be possible to import a save dump from the Win32 version and copy files from the mc0/mc1 folders to the same location on your Android device.

**Comment by gambrio** [comment] 2015-05-26 17:35
@jpd002 Yeah, it doesn't work. I imported the saves from Sharkport files and Play! detected them correctly as Kingdom Hearts saves. I opened the folder where all the data was imported to (e.g., system, icon, save itself, etc.) and copied that to a folder I made called "BASLUS-20370," similar to other saves I had there from testing (inside mc0 inside of vfs in "Play Data Files" on my NAND storage/Android drive), and copied all of the Kingdom Hearts data there and when I load KH there and pick "Load Game" nothing appears. 

Any idea what I might have done wrong?

**Comment by jpd002** [comment] 2015-05-27 04:27
528dd125f7b79643fb307e92f0edd1b3253719db Should fix the "half-screen" issue in KH and other games.

As for the save game, I tried it on my side and it worked. Here's what my directory layout looks like (I've got two save files):

* Play Data Files
  * vfs
    * mc0
      * BASLUS-20370-01
        * BASLUS-20370-01
        * icon.sys
        * mc_icon.bin
        * system.bin
      * BASLUS-20370-03
        * BASLUS-20370-03
        * icon.sys
        * mc_icon.bin
        * system.bin

The load game menu looks blank on Android in the current weekly even though there's valid files in there. So what you did might have worked even though you couldn't see anything.

**Comment by gambrio** [comment] 2015-05-27 18:03
Alright, I finally solved the issue on my side too, and unfortunately the rendering is very bad and I can't move Sora with the directional pad (I think the analog stick is needed to move characters, but not too sure):

![100_0889](https://cloud.githubusercontent.com/assets/12025386/7843622/bfde178c-0478-11e5-9468-fdc9432dc722.JPG)

This is a Sharkport save at the last world. I can jump and open the menu, but visuals are garbled big time.
The "half bodies issue" appears to be the same rounding issue as was formerly in the Windows/OS X builds.

**Comment by jpd002** [comment] 2015-05-28 03:42
Rendering will be improved a bit in next weekly as I've re-enabled flags checking in VU on Android.

![img_0291](https://cloud.githubusercontent.com/assets/6760433/7852296/86bed026-04c9-11e5-89a4-9cf81b845280.JPG)

You're right about the "half body issue", it's caused by the same rounding issue. Unfortunately, changing the FPU rounding mode on AArch32 doesn't change the behavior of the NEON instructions, so, it won't be easy to fix (but possible still).

**Comment by gambrio** [comment] 2015-05-28 04:00
@jpd002 You mean you'd have to implement a different way of handling rounding with the NEON extension?

**Comment by jpd002** [comment] 2015-05-28 04:23
@gambrio Still unsure about the best way to fix that. The PS2's FPU has lots of peculiarities and working around them is quite a pain especially in this case where rounding modes differs on the various supported architectures (x86 and ARM). I'm leaning towards implementing some kind of software FPU that would be jitted which would guarantee 100% accuracy, but I'm not sure how much it will affect the emulator's speed.

**Comment by jpd002** [comment] 2015-05-29 06:09
@edwardmx96 Slowness for KH2 seems to come from the emulator constantly jitting blocks. The game calls FlushCache(ICACHE) repeatedly and I was using that function call as an hint to clear the block cache (that was needed for some games). Disabling that behavior fixes the lag, but it might break other games too, so, I'll have to do some more tests.

**Comment by edwardmx96** [comment] 2015-05-31 03:17
@jpd002 and @gambrio thanks for the help. I understand now.

**Comment by edwardmx96** [comment] 2015-05-31 04:22
@jpd002 how do you feel so far about building the android port? Does emulating the PSP and PS2 differ? I have used PPSSPP and it makes me wonder because bother of the systems have close to the same graphics. I am guessing they would differ because of the PS2 cpu architecture. I'm not sure and kinda new to this stuff.

**Comment by jpd002** [comment] 2015-06-08 04:01
Just so that people know, I'm still working on this. I'm currently reworking the way cached JIT blocks are invalidated when new code is written in RAM (https://github.com/jpd002/Play-/tree/vm_blockcache). It's now using the host's virtual memory to detect potential invalid blocks instead of inspecting every memory write manually (a bit like what was suggested in #39). This should improve the emulator's speed with every game.

@edwardmx96 Porting to Android isn't too bad, but it's still early in development, so things might get a bit complicated later (ie.: GPU differences, differences in floating point handling on x86 and ARM, etc.) I don't know much about the PSP's architecture, so I can't really tell what are the differences.

**Comment by jpd002** [comment] 2015-06-10 05:15
The branch has been merged in master, so, KH2 won't lag anymore in the next weekly. Game is not yet playable though.

**Comment by jpd002** [comment] 2015-06-15 02:32
KH2 shouldn't lag anymore in latest weekly build (2015-06-14), so, I'm closing this issue. I will work on getting KH2 playable later.

**Closed by jpd002** 2015-06-15 02:32 UTC
Labels: bug
