### ISSUE TITLE
Can't assign RT and LT on my Xbox One controller

### ISSUE THREAD

**Issue by calebh514** [jpd002/Play-#631] opened 2017-09-07 21:13 UTC
Whenever I try and assign either of the triggers to a button the emulator doesn't recognize the input. This is on Play! v0.30 and a Windows 10 Pro (1607) system. It isn't the official Xbox One controller, it's a third party one, specifically this one. 

https://www.amazon.com/dp/B01K3VMBYS

Unfortunately I don't have any other controllers around to test. For reference this problem doesn't occur anywhere else, in any games or emulators I use.

**Comment by jpd002** [comment] 2017-09-08 20:23
This is probably due to the fact that I'm using DirectInput and not XInput on Windows. Related issue: #4.

**Comment by jpd002** [comment] 2018-03-21 20:45
Closing this since it's a duplicate of #4.

**Closed by jpd002** 2018-03-21 20:45 UTC
