### ISSUE TITLE
(Windows) Clock Tower 3 : In game but black screen

### ISSUE THREAD

**Issue by n1dminhd** [jpd002/Play-#250] opened 2015-07-22 16:11 UTC
Play! 22-07-2015 Windows 7 64bit

![untitled 3 5](https://cloud.githubusercontent.com/assets/4449742/8830517/c27053e6-30c6-11e5-9fa6-3e5480e736a9.jpg)

![untitled 4](https://cloud.githubusercontent.com/assets/4449742/8830519/c7bc6358-30c6-11e5-8f9f-c5c37dab3133.jpg)

But, after : 

![untitled 5](https://cloud.githubusercontent.com/assets/4449742/8830542/eb97833e-30c6-11e5-82b2-de54a48b1eb2.jpg)

**Comment by johnnyleap** [comment] 2015-09-21 23:38
Pretty sure it doesn't go in-game yet ... it does get to the menu screen but doesn't respond to input, which seems to be the exact same problem with some other titles and similar to games not finding the DS2:

![cte1ing](https://cloud.githubusercontent.com/assets/13894398/10007972/680a166c-60b9-11e5-8070-61da40ab7a66.jpg)

**Comment by jpd002** [comment] 2015-09-22 02:42
@johnnyleap I've noticed that the broken input problem seems to happen randomly on some games. Resetting the game can sometimes make input work. (I know what's causing this, but I haven't pushed a fix yet).

**Comment by johnnyleap** [comment] 2015-09-22 03:05
Yeah, I can confirm that, but with some games the issue is not random and is more permanent.

I reset this game like 10 times and it won't work, but input seems to work early on because the intros can be skipped by pressing 'X', but at the menu nothing works at all. Games with permanent lack of input on Play!, that I know of, are: Destroy All Humans! (1 and 2; input never detected, but haven't tested recently); Rainbow Six 3 (no controller detected); Animaniacs: The Great Edgar Hunt (lcan't proceed because input doesn't register either); and a few others in the compatibility list, I believe.

**Comment by jpd002** [comment] 2015-09-22 04:26
@johnnyleap Ah, thanks for testing that. Yeah, if it doesn't work after 10 times, it probably means something is screwed up in the IOP (as it is probably the case with the games you've listed).

**Comment by jpd002** [comment] 2018-03-30 15:29
Indeed! Thanks!

**Closed by jpd002** 2018-03-30 15:29 UTC
Labels: bug
