### ISSUE TITLE
you should team up with henrik rydgard the psspp emulator developer

### ISSUE THREAD

**Issue by Jordanesquivez** [jpd002/Play-#459] opened 2016-09-08 19:40 UTC
I think if u joined up with another emulator developer I think the app can be complete in 5 more months.. with your skills and his... anything is possible

**Comment by Fadi5555** [comment] 2016-09-08 20:40
I'm completely with you on this. It's been long time without anything new on this project.
Because he's working alone. It's time to join with other teams. To take all advantages of working as a group.

**Comment by minuteworld** [comment] 2016-09-08 22:54
Talk to some of the hundreds of dolphin Davis and pcsx2 devs. Maybe if more people knew about the project, more people would contribut

**Comment by Jordanesquivez** [comment] 2016-09-08 23:06
Minuteworld that would make the app even betterr than ppsspp and all emulator that exist on every type of platform

**Comment by minuteworld** [comment] 2016-09-09 00:11
Yeah it will so advertise the project on their respective forum. Let's give this guy kickback.

**Comment by minuteworld** [comment] 2016-09-09 00:13
Also maybe not the pcsx2 devs... We don't want decades of shit code.

**Comment by Jordanesquivez** [comment] 2016-09-09 00:35
Yeah its simple as team work

**Comment by zuzma** [comment] 2016-09-09 03:34
It's not simple. One they have to know about ps2 hardware and two need to have free time. I'd say most of them don't meet one or both requirements

**Comment by Jordanesquivez** [comment] 2016-09-09 03:49
Zuzma thats true but they all have experienced and are experts

**Comment by zuzma** [comment] 2016-09-09 04:04
Well yeah they do have experts, but like I said they're already working on another project so i doubt they have much free time. Besides It's up to jpd002 if he wants to work with someone else or not. Also FYI those other projects you mention already are aware of play! so advertising it wont help

**Comment by minuteworld** [comment] 2016-09-09 04:08
I mean i'm sure you can find SOME people that are willing to contribute to this this. The main dev can advertise the project on emulation centric forum, computer forums, tech communes and fucking reddit.

As much as I HATE reddit and the subhumans that lurk there, I'm sure the dev could find people on r/pcgaming, the non retards on r/pcmasterrace and one r/emulation hell I think some emulator devs lurk at r/emulation. Go shill on the /tech/ on various imageboards. I'm sure you'd be able to find some coders that are willing to learn the code and people to test the newest weekly builds.

Just try and make yourselfs know. I have tremendous faith in the project and I don't wanna see it die if I the creator ever stops working.

**Comment by zuzma** [comment] 2016-09-09 04:09
People are already helping play! out. Otherwise he'd not be getting any pull requests. Uknownbrackets maintains the ps2autotests and is a ppsspp dev

**Comment by minuteworld** [comment] 2016-09-09 04:28
But I mean I'm not so used to github and i'm not a coder but it looks like that the dev you mentioned only contributed alittlebit at the beginning of man and the rest of the 13 contributors that aren't the top 2 are doing even less than that. I'm probably just talking out of my ass but I think you need to get more than 13 people.

Ofcouse you don't NEED to do anything or listen to the rantings of a sad neckbeard emulation enthusiast, I just really really want you guys to succeed and to do that, you need more people passionate about this and when I sat passionate, I don't mean a dev to come in, leave one line of code and forget like lioncash.

If you are a dev, i m not telling what to do or anything. I'm just saying there's noharm in in a little advertising. On YouTube, I can look for any emulator I want and I see videos of it buy when I type in "play! Ps2 emulator", I see less than 8 results. That's saying something.

**Comment by minuteworld** [comment] 2016-09-09 04:34
Im still going to test this on android though. I still can't believe mosy my one guy got a ps2 to work on 200$ android devices

**Comment by zuzma** [comment] 2016-09-09 04:34
Well you can go out and advertise if you like, I'm just a really negative person lol

**Comment by minuteworld** [comment] 2016-09-09 04:35
I'm probably more negative than you when I'm not talking about emulation, lol.

**Comment by Thunder07** [comment] 2016-09-09 10:33
I was hoping this discussion wouldn't pour over to github, it's not 'exactly' a development topic.
but since it's here, its up to jean to close it if he chooses to, for now I'll add my two cents.

1) Most of those devs you're talking about do know about this emulator. (not all surely)
2) the issue is, as Zuzma mentioned, its one thing being an expert at one thing, its another being free and with specific PS2 knowledge. (although there are still a lot of thing to do that aren't PS2 specific)
3) most people who mention this project, and this is also evident on this thread, only talk about the android aspect... android devices with the exception of very few are not strong enough yet, so when people 'advertise' a PS2 android emulator, a lot of devs are probably put off.
4) zuzuma mentioned it's up to jean if he wants help or no, yes and no, this is an open source project on github, everyone is free to send PRs, but its up to jean to accept/reject those PR, beside quality control, its unlikely a PR will be rejected.
5) advertisement for help, should probably come from Jean himself, he's the one person thats most probably equipped and familiar with the shortcoming and required changes for the projects
6) linked to point 3, a lot of random users don't understand how progress works with these projects, so for example, my PR is 30 commits to include a linux UI is in their eyes is no progress, since the emulator now 'isn't any better' on android, this is also evident from just reading random 'advert' and comments online.

**Comment by minuteworld** [comment] 2016-09-09 11:34
I agree that there are a lot of people are ignorant about how emulation projects works.

Also I know full well that this is not a forum, I just joined in because this is the only place to openly get in contact with the devs (there's also reddit but I'm not going back there) so forgive us. I've been looking at the older commits and I saw someone mention a forum. Maybe if you had like a small forum linked on the github and the main site, it might cut down on the useless threads. You'd probably still get some who are not smart enough to read the site/github page here make forum-like threads here but a four. Might cut abit down on that.

**Comment by Jordanesquivez** [comment] 2016-09-09 13:56
If people are aware of this emulator why not donate?? if jean doesnt need or want a team people should donate ... this can help the developer to purchase equipment or software programs and also the latest phones to test games on.. and even more..to make the emulator finishes more faster

**Comment by MoochMcGee** [comment] 2016-09-09 14:03
JEAN IS DOING THIS IN HIS FREE TIME. THIS IS A PROJECT FOR FUN AND
LEARNING, STOP BEING SUCH IDIOTS ABOUT IT.

**Comment by zuzma** [comment] 2016-09-09 14:27
That's true that there's other stuff to work on like the UI that's not emulation related. Eh I do feel dumb using the word advertise, I was talking about attracting more users not getting devs.

**Comment by Thunder07** [comment] 2016-09-09 16:04
@minuteworld i know and a forum is definitely needed, i did talk to Jean about it, but he probably didn't get the time to consider it and give me an answer. there is no harm in using github to get the msg across, but I personally don't want all the fanboys spamming it too with useless issues, such as "eta updates", we've had incidents before.

@Jordanesquivez because Jean is not currently accepting donations, as in there is no actual way to donate even if you wanted. just so, even without donations, Jean has purchased phones, tablets before for the project. (android MiPad tablet, nvidia shield, iPhone (or i might have been an ipad) ).
if i had to guess, jean probably considers the payment, payment usually entitle work, and he doesn't feel comfortable taking money when he doesn't know how much work he'd be able to put into the project at any one time. (perhaps paying for a full years salary will work :p )

@zuzma while it will be great having more users, personally i see little point for the moment.

**Comment by zuzma** [comment] 2016-09-09 17:36
@Thunder07 Ah alright. I was just thinking of posting some videos for fun to /r/emulation but I don't care either way. Sorry for clogging up the bugtracker with bs. btw

**Comment by Thunder07** [comment] 2016-09-09 17:53
@zuzma you're free to do so if you wish, no one will stop you nor will anyone complain.  (people have posted videos before)
hell, no one would stop you from blastering every emulation forum asking them to help this project.
but you'll probably be told off on such forum.

the issue im making is really not even directed at you too, but its at those who are 'discussing' the magic team to finish this project, sure we can all hope for that, but generally speaking open source devs join projects because they want too. aka I'm merely trying to set peoples expectations.

**Comment by jpd002** [comment] 2016-09-10 05:26
Thanks everyone for your interest in the project. I will gladly accept any input from anyone, either it be pull requests or bug reports. I'm also open to suggestions to make the project more accessible to people who would like to contribute.

Also, I think most people know about this project by now, so, I don't think advertising would do much, even though I appreciate the intention. Money won't really help either, it's not really a "resources" problem.

Well, closing this since it's not really an "issue". I really need to revisit the idea of opening a forum.

**Closed by jpd002** 2016-09-10 05:26 UTC

**Comment by 389abhaysingh** [comment] 2017-09-20 03:45
Happy to hear you have an MiPad :P
@jpd002

**Comment by 389abhaysingh** [comment] 2017-09-20 03:46
Please don't stop development for 32bit devices like MiPad and shield tablet they are equally or in some cases more powerful than 64bits

**Comment by jpd002** [comment] 2017-09-21 21:35
One annoying thing with AArch32 is that it doesn't have the nice floating point SIMD operation rounding modes that give results that are close to what the PS2 does. 32-bits support will remain, but it still needs some work to be on par with 64-bits.
