### ISSUE TITLE
Error compiling new checkout

### ISSUE THREAD

**Issue by bigianb** [jpd002/Play-#787] opened 2019-08-23 13:58 UTC
I just grabbed the latest masters of the code on a new machine and decided to use the Qt designer way of compiling rather than cmake for Visual Studio (i.e. following the recommendation). When compiling I get the error that nmake doesn't know how to build Pch.h ... which is somewhat odd as the file exists (I guess it is a working directory error). Qt designer does not give me much info though, so difficult to track down. Any ideas?
Checkout info and logs are below...

Checkout Info:

```
Microsoft Windows [Version 10.0.17134.885]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\dev\play>git clone https://github.com/jpd002/Play-.git
Cloning into 'Play-'...
remote: Enumerating objects: 312, done.
remote: Counting objects: 100% (312/312), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 39069 (delta 180), reused 181 (delta 124), pack-reused 38757 eceiving objects: 100% (39069/39069), 15.64 MReceiving objects: 100% (39069/39069), 15.69 MiB | 10.43 MiB/s, done.

Resolving deltas: 100% (29552/29552), done.

C:\dev\play>git clone https://github.com/jpd002/Play--CodeGen.git
Cloning into 'Play--CodeGen'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 6372 (delta 31), reused 44 (delta 26), pack-reused 6307
Receiving objects: 100% (6372/6372), 1.67 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4984/4984), done.

C:\dev\play>git clone https://github.com/jpd002/Play--Framework.git
Cloning into 'Play--Framework'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 5353 (delta 54), reused 63 (delta 46), pack-reused 5272
Receiving objects: 100% (5353/5353), 890.76 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3759/3759), done.

C:\dev\play>git clone https://github.com/jpd002/Play-Dependencies.git
Cloning into 'Play-Dependencies'...
remote: Enumerating objects: 3461, done.
remote: Total 3461 (delta 0), reused 0 (delta 0), pack-reused 3461
Receiving objects: 100% (3461/3461), 8.63 MiB | 6.10 MiB/s, done.
Resolving deltas: 100% (786/786), done.

C:\dev\play>git clone https://github.com/jpd002/Nuanceur.git
Cloning into 'Nuanceur'...
remote: Enumerating objects: 534, done.
Receiving objects: remote: Total 534 (delta 0), reused 0 (delta 0), pack-reused 534
Receiving objects: 100% (534/534), 76.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (284/284), done.

C:\dev\play>cd Dependencies

C:\dev\play\Dependencies>git submodule update --init
Submodule 'SDWebImage' (https://github.com/rs/SDWebImage.git) registered for path 'SDWebImage'
Submodule 'boost-cmake' (https://github.com/jpd002/boost-cmake.git) registered for path 'boost-cmake'
Submodule 'nlohmann_json' (https://github.com/nlohmann/json.git) registered for path 'nlohmann_json'
Cloning into 'C:/dev/play/Dependencies/SDWebImage'...
Cloning into 'C:/dev/play/Dependencies/boost-cmake'...
Cloning into 'C:/dev/play/Dependencies/nlohmann_json'...
Submodule path 'SDWebImage': checked out '0df32ea232aca587d5b67760b7f877079c51966c'
Submodule path 'boost-cmake': checked out 'e97843ed8d7d069a278e6f2adf33a9f91638c73f'
Submodule path 'nlohmann_json': checked out '676c847c558fe13abebfec5fece318ed9dd4d432'

C:\dev\play\Dependencies>cd ..

C:\dev\play>dir
 Volume in drive C has no label.
 Volume Serial Number is 4AF5-41D7

 Directory of C:\dev\play

23/08/2019  13:34    <DIR>          .
23/08/2019  13:34    <DIR>          ..
23/08/2019  13:53    <DIR>          build-Play-Desktop_Qt_5_13_0_MSVC2017_64bit-Default
23/08/2019  12:08    <DIR>          CodeGen
23/08/2019  12:09    <DIR>          Dependencies
23/08/2019  12:09    <DIR>          Framework
23/08/2019  12:10    <DIR>          Nuanceur
23/08/2019  13:46    <DIR>          Play
               0 File(s)              0 bytes
               8 Dir(s)  121,133,088,768 bytes free

C:\dev\play>
```
compile log:

```
13:56:57: Running steps for project Play...
13:56:57: Starting: "C:\Program Files\CMake\bin\cmake.exe" --build . --target all
[  9%] Built target Framework_Win32
[  9%] Built target sqlite3static
[  9%] Built target Boost_system
[ 11%] Built target Boost_filesystem
[ 14%] Built target zlibstatic
[ 26%] Built target Framework
[ 26%] Built target Framework_Http
[ 32%] Built target CodeGen
[ 34%] Built target glew_s
[ 36%] Built target bz2
NMAKE : fatal error U1073: don't know how to make 'Pch.h'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
13:57:02: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project Play (kit: Desktop Qt 5.13.0 MSVC2017 64bit)
When executing step "CMake Build"
13:57:02: Elapsed time: 00:06.
```

**Comment by bigianb** [comment] 2019-08-23 16:06
more info.
If I do:
```
cmake .. -G"Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH="C:\Qt\5.13.0\msvc2017_64" -DUSE_QT=YES
```

The do:
```
cmake --build . --config Release
```
then the build fails in autotest:

```
gsh_d3d9.lib(GSH_Direct3D9_Shader.obj) : error LNK2019: unresolved external symbol D3DCompile referenced in function "p
rivate: class Framework::Win32::CComPtr<struct IDirect3DPixelShader9> __cdecl CGSH_Direct3D9::CreatePixelShader(struct
CGSH_Direct3D9::SHADERCAPS)" (?CreatePixelShader@CGSH_Direct3D9@@AEAA?AV?$CComPtr@UIDirect3DPixelShader9@@@Win32@Framew
ork@@USHADERCAPS@1@@Z) [C:\dev\play\Play\build\tools\AutoTest\autotest.vcxproj]
C:\dev\play\Play\build\tools\AutoTest\Release\autotest.exe : fatal error LNK1120: 1 unresolved externals [C:\dev\play\P
lay\build\tools\AutoTest\autotest.vcxproj]
```

If I open the sln in VS 2017 and select Play as the target then it compiles and runs just fine. The compiling all gives the same autotest error.

So in summary, it compiles fine from the VS 2017 IDE when selecting Play as the startup project but the instructions as written in the readme fail.

**Comment by Zer0xFF** [comment] 2019-08-23 23:09
for the DirectX linking issue, we're not linking against any library if  you dont specify specific build tool, `-T v141_xp`.
 to fix this we need to link against `Source\gs\GSH_Direct3D9\CMakeLists.txt`

```diff
--- a/Source/gs/GSH_Direct3D9/CMakeLists.txt
+++ b/Source/gs/GSH_Direct3D9/CMakeLists.txt
@@ -18,6 +18,11 @@ if(CMAKE_GENERATOR_TOOLSET MATCHES "_xp$")
                )
        endif()
        list(APPEND gsh_d3d9_PROJECT_LIBS d3dcompiler)
+else()
+       find_package(DirectX9 REQUIRED)
+       if(DirectX_D3D_FOUND)
+               list(APPEND gsh_d3d9_PROJECT_LIBS ${DirectX_D3DCOMPILER_LIBRARY})
+       endif()
 endif()
```

for the qt issue, i assume you meant creator and not designer? as I believe the designer is only to edit Qt ui files?
eitherway, try changing nmake to ninja, see if that helps. I'll look into that one 2morrow when i get a chance

**Comment by jpd002** [comment] 2019-09-27 17:10
I've merged the d3dcompiler fix for non WinXP builds: https://github.com/jpd002/Play-/commit/3e810945ae477ecb46c1b0de849c4d6de82e615a.

Is there still an issue with building from Qt designer?

**Comment by Zer0xFF** [comment] 2019-09-28 16:27
just tried to build using Qt Creator and im getting the `Pch.h` error, which seems to be caused by outdated `PrecompiledHeader.cmake` script, the original repo seems to have been unmaintained for the last 3 years (which is the copy we're using) this [fork ](https://github.com/dutow/cmake-precompiled-header) while havn't recieved any updated in the last 2 years, has a path related fix, which fix this issue

**Comment by jpd002** [comment] 2019-09-29 14:42
Could we replace our copy with that updated version?

**Comment by Zer0xFF** [comment] 2019-09-29 20:22
yes, ill send a PR once I get the chance

**Comment by jpd002** [comment] 2019-10-03 17:24
We should be good now. Closing this.

**Closed by jpd002** 2019-10-03 17:24 UTC
